### ISSUE TITLE
[M0 - Dev] Fechas en Ruta y Tramo

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#10]
Hola, abro este issue porque tengo un problema relativo a los atributos que indican la fecha de cada tramo o cada ruta, el cual se me ha pasado comentar en el issue #8.

¿Es posible que una ruta tenga tramos de fechas de distintas? Si es así debería añadir solo el atributo fecha en la clase Tramo, si vas a restringir el dominio del problema a rutas que sean solo en el mismo día, tal vez sí debería añadir el atributo fecha en la clase Ruta y no ponerlo en la clase Tramo.

Ya me dices cómo hacerlo!

**Comment by MarinoFajardo** [comment]
Tienes razón, el atributo fecha habría que ponerlo en la clase ruta, ya que las paradas de una ruta tienen que estar dentro de un tramo horario.

**Comment by PacoCP5** [comment]
Genial, pues dejamos el atributo fecha en la clase Ruta!

**Comment by MarinoFajardo** [comment]
Perdona que te lo diga ahora pero también será necesario que la clase tramo tenga un atributo fecha, ya que la duración de la ruta será la diferencia entre la fecha de la última parada y la fecha de la primera. Un Saludo.

**Comment by PacoCP5** [comment]
Hola de nuevo, perdona pero no me termino de aclarar, la duración de la ruta se calcula sumando el tiempo de cada tramo no? Entonces ahí la fecha no habría que ponerla (también se podría ver con la fecha del tramo inicial y el tramo final, pero creo que te ahorras un atributo en cada objeto de la clase Tramo si lo hacemos de la otra forma).

**Comment by MarinoFajardo** [comment]
Vale, hazlo como lo has propuesto y lo vemos.
