### ISSUE TITLE
[M0 - Dev] Duda sobre la mutabilidad de la clase Tramo

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#11]
Hola,

Abro este issue para ver en qué clase vas a implementar la lógica de negocio. Creo que lo harías desde la clase Ruta no? y así los objetos de la clase Tramo tendrían valores fijos una vez se han creado, es decir no cambiarían, a diferencia de la clase Ruta, en la cual sí que puedes ir añadiendo y retirando nuevos tramos para ver la ruta optima según las distintas HUs.

Esta aclaración es para definir los objetos valor y las entidades. Si es como pienso la clase Tramo sería un objeto valor y la clase Ruta sería una entidad. 

Si estoy equivocado en algo me dices :smile_cat:

**Comment by MarinoFajardo** [comment]
Justo como lo has dicho , la clase tramo va a ser nuestro objeto valor mientras que la clase ruta será nuestra entidad.
