### ISSUE TITLE
[M0 - Dev] Gestión de errores en la clase Tramo

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#12]
Hola, este issue es para ver cómo quieres que gestione la introducción de datos incorrectos en el constructor de la clase Tramo, por ejemplo si el precio es negativo o el tiempo es negativo o nulo.

En principio, había pensado lanzar una excepción con un mensaje, pero no sé si quieres que en ese caso siga inicializando el atributo a -1 o a algún valor similar para que no se quede a null.

Ya me dices!

**Comment by MarinoFajardo** [comment]
En principio hazlo como has dicho, si en el pull request veo algo que quiero cambiar te lo pongo :)
