### ISSUE TITLE
[M0 - Dev] Lenguaje de programación

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#13]
Lenguaje de programación

_Originally posted by @PacoCP5 in https://github.com/MarinoFajardo/ControlaTuGasto/issues/2#issuecomment-1293355175_

**Comment by PacoCP5** [comment]
Como he comentado este issue es para plantear el problema de elegir el lenguaje de programación con el que implementar la representación del modelo.

**Comment by MarinoFajardo** [comment]
Buenas @PacoCP5, vamos a trabajar con typeScript.
