### ISSUE TITLE
[M0 - Dev] Concepto de Ruta

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#14]
Por otro lado, en tu HU aparece el concepto de ruta, con lo cual me encuentro con el problema de representar el concepto, así que abro un issue relativo a esto.

_Originally posted by @PacoCP5 in https://github.com/MarinoFajardo/ControlaTuGasto/issues/2#issuecomment-1293385421_

**Comment by PacoCP5** [comment]
He pensado que una Ruta puede ser una colección de tramos conectados los unos con lo otros, para así que en tu lógica de negocio puedas añadir y quitar tramos viendo el precio resultante para así ver cuál es la más barata.

**Comment by MarinoFajardo** [comment]
Efectivamente, en el contexto del problema que se quiere resolver en las historias de usuario, una ruta será una colección de tramos unidos entre ellos.
