### ISSUE TITLE
[M0 - Dev] Concepto de Tramo

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#15]
He pensado que una Ruta puede ser una colección de tramos conectados los unos con lo otros, para así que en tu lógica de negocio puedas añadir y quitar tramos viendo el precio resultante para así ver cuál es la más barata.

_Originally posted by @PacoCP5 in https://github.com/MarinoFajardo/ControlaTuGasto/issues/14#issuecomment-1293391445_

**Comment by PacoCP5** [comment]
Asociado a representar el modelo con el objetivo de cumplir el milestone M0 y fijándome en la HU #2 he pensado que para el concepto de ruta lo mejor para la lógica de negocio es que sea una colección de tramos, y en este issue vemos el concepto de tramo.

**Comment by MarinoFajardo** [comment]
En este contexto un tramo es el recorrido que hay entre dos paradas de autobuses.

**Comment by PacoCP5** [comment]
De acuerdo, entonces de aquí surge el concepto de parada, así que asociada a esto crearé otro issue para discutir el problema de su representación, ya que es distinto a este.
