### ISSUE TITLE
[M0 - Dev] Concepto de Parada

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#16]
De acuerdo, entonces de aquí surge el concepto de parada, así que asociada a esto crearé otro issue para discutir el problema de su representación, ya que es distinto a este.

_Originally posted by @PacoCP5 in https://github.com/MarinoFajardo/ControlaTuGasto/issues/15#issuecomment-1293413934_

**Comment by PacoCP5** [comment]
Como hemos comentado en el issue #15 hay que ver la representación de una parada.

**Comment by JJ** [comment]
Conviene también que este issue específico se relacione con una HU, como todos los demás. Aunque esté relacionado de forma indirecta a través de otro issue, se evita navegación si se hace así.
