### ISSUE TITLE
[M2] Algoritmo para el cálculo de rutas

### ISSUE THREAD

**Issue by MarinoFajardo** [MarinoFajardo/ControlaTuGasto#40]
Para resolver el problema, es necesario implementar un algoritmo sobre la estructura de datos que calcule la ruta más barata. Este algoritmo debe calcular el coste de llegar desde el nodo root hasta cada hoja del árbol, ya que, como hemos dicho anteriormente, el nodo root representa el origen de la ruta y las ramas del árbol los caminos para llegar al destino. Tras calcular el coste de cada rama debe comprobar si es menor que el de la rama con menor coste actual y devolver el coste de la ruta más barata.

**Comment by JJ** [comment]
Para resolver el problema adecuadamente, debes pensar cómo encapsular las estructuras de datos que necesitas para que quien usa el algoritmo no se preocupe de qué algoritmo usa, simplemente de lo que quiere obtener.
En ese sentido, "plantear el problema" implica crear un issue que diga el programador qué tiene y qué es lo que quiere. A partir de ahí se van desgranando las diferentes funciones, pero es esencial que sepas claramente qué es lo que hace falta para programarlo bien.
