### ISSUE TITLE
[M0 - Dev] Atributos de las clases Tramo y Ruta

### ISSUE THREAD

**Issue by PacoCP5** [MarinoFajardo/ControlaTuGasto#8]
Hola, hasta ahora llevo los siguientes atributos para las clases que describen el modelo del problema:

- Tramo:
  + origen_tramo
  + destino_tramo
  + precio
  + tiempo

- Ruta
  + origen_ruta
  + destino_ruta
  + tramos (Colección de tramos)

Tengo la duda de si en Ruta debería añadir tiempo_total y precio_total para que así sepas el precio y el tiempo final de una ruta concreta, pero como son atributos que se calcularían en base a la colección de tramos no lo tengo muy claro.

Si ves que cualquier atributo no te cuadra no dudes en decírmelo. :smile:

**Comment by MarinoFajardo** [comment]
En cuanto los atributos me parece correcto, yo añadiría lo que has dicho en la clase ruta ya que es lo que queremos calcular. Además habría que hacer que el tiempo y el precio sean valores correctos y no puedan ser negativos. Otra cuestión es, ¿cómo vas a organizar estos ficheros dentro del repositorio? Hazme una propuesta y te digo si es correcto.

**Comment by JJ** [comment]
Este issue no describe un problema. Por favor, mirad errores frecuentes en la sesión de la semana 7 y anteriores. Tampoco está enlazado a una historia de usuario.
